app:
  name: "effective"
  env: "STAGE"
http:
  port: "8080"
  bind: "0.0.0.0"
api:
  age_url: "https://api.agify.io"
  gender_url: "https://api.genderize.io"
  nationality_url: "https://api.nationalize.io"
db:
  url: "postgres://postgres:postgres@localhost:5432/qolio_extender?sslmode=disable"
  connect_time_out: 5
  auto_create: true
proc:
  source_call_topic: "3cx.events-STAGE"
  call_sync: true
  text_sync: true
  time_zone: "Europe/Minsk"
  last_not_completed: "2024-01-09" # YYYY-MM-DD
  sync_freq: 5 # minutes
  filter_freq: 10 # minutes
broker:
  hosts:
qolio:
  email:
  password:
  url: "https://api.prod1.qolio.ru"
  phone_call_url: "secret"
  phone_call_token: "secret"
  text_url: "secret"
  text_token: "secret"
  calls_organization_id: "b93c90ae-1f0b-448a-b9bc-1989cb0ad81d"
useresponse:
  url: "https://useresponse.chezaja.by/api/7.0"
  email:
  password:

